### select everything
POST http://localhost:8082/search
Content-Type: application/json

{
    "yql": "select * from doc where true"
}

### insert a document
POST http://localhost:8082/document/v1/default/doc/docid/582d3b9d-9b57-4a54-b183-eed6f0455763
Content-Type: application/json

{
    "fields": {
        "body": "hello world manually"
    }
}

### delete everything
DELETE http://localhost:8082/document/v1/default/doc/docid?selection=true&cluster=content

## in Vespa Cloud
curl --key /Users/radu/.vespa/$VESPA_CLOUD_APP_NAME/data-plane-private-key.pem --cert /Users/radu/.vespa/$VESPA_CLOUD_APP_NAME/data-plane-public-cert.pem -XDELETE 'https://'$VESPA_CLOUD_ENDPOINT'/document/v1/default/doc/docid?selection=true&cluster=content'